name: synka

services:
  synka:
    image: ghcr.io/synka-org/synka
    container_name: synka
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__Sqlite: Data Source=/app/data/synka.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
