name: PR Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Restore dependencies
      run: dotnet restore Synka.slnx
      
    - name: Build
      run: dotnet build Synka.slnx --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test Synka.slnx --no-build --configuration Release --verbosity normal

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Restore dependencies
      run: dotnet restore Synka.slnx
      
    - name: Check formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic
      
    - name: Run analyzers
      run: dotnet format analyzers --verify-no-changes --verbosity diagnostic
